[compat]
AdaptiveRejectionSampling = "0.1.1"
AdvancedHMC = "0.2"
ArgCheck = "1, 2.0"
ArraysOfArrays = "0.4, 0.5"
BAT="1.0.1"
Bijectors = "0.7, 0.8"
CPUTime = "1.0"
Clustering = "0.13, 0.14"
Colors = "0.9,0.10,0.11, 0.12"
DataStructures = "0.17, 0.18"
DiffResults = "1"
Distributions = "0.21.10, 0.22, 0.23"
DistributionsAD = "0.5, 0.6"
DoubleFloats = "0.9, 1"
ElasticArrays = "1.2.3"
EmpiricalDistributions = "0.1"
FFTW = "1"
FillArrays = "0.7,0.8, 0.9"
ForwardDiff = "0.10"
HypothesisTests = "0.10"
IntervalSets = "0.5"
KernelDensity = "0.5, 0.6"
LaTeXStrings = "1"
Measurements = "2"
NLSolversBase = "7"
NamedArrays = "0.9"
Optim = "0.19,0.20, 0.21, 0.22"
PDMats = "0.9, 0.10"
ParallelProcessingTools = "0.4"
Parameters = "0.12"
PositiveFactorizations = "0.2"
ProgressMeter = "1"
QuadGK = "2"
Random123 = "1.2"
RecipesBase = "0.7, 0.8, 1.0"
Requires = "0.5, 1"
Sobol = "1.4"
SpecialFunctions = "0.10"
StatsBase = "0.32, 0.33"
StructArrays = "0.4"
Tables = "0.2, 1.0"
TypedTables = "1.2"
ValueShapes = "0.6.10"
julia = "1.3"

